-- Generated by backport-tools/prepare_unitframe_media.py.
local _, ns = ...
local paths = ns.Wrath.BarTexturePaths
paths[ [[interface\addons\ellesmereui\media\combat\combat0.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat0.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat1.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat1.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat2.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat2.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat3.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat3.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat4.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat4.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat5.tga]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat5.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat-indicator-custom.png]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat-indicator-custom.tga]]
paths[ [[interface\addons\ellesmereui\media\combat\combat-indicator-class-custom.png]] ] = [[Interface\AddOns\EllesmereUIUnitFrames\Media\Art_335\combat\combat-indicator-class-custom.tga]]
