"""Encode the non-power-of-two Core bar art as module-owned Wrath TGAs.

Leaves the accepted Core assets unchanged. Expands rows to the next power of
two, keeping the full pattern across the fill, and emits uncompressed BGRA32.
"""
from pathlib import Path
import re
import struct

root = Path(__file__).resolve().parents[1]
core = (root / 'EllesmereUI/EllesmereUI.lua').read_text(encoding='utf-8-sig')
catalog = core.split('EllesmereUI.BAR_TEXTURE_FILES = {', 1)[1].split('}', 1)[0]
names = sorted(set(re.findall(r'"([^"\n]+\.tga)"', catalog)))
target = root / 'EllesmereUIUnitFrames/Media/Textures_335'
target.mkdir(parents=True, exist_ok=True)
converted = []
for name in names:
    source = (root / 'EllesmereUI/media/textures' / name).read_bytes()
    id_size, cmap, kind, _, _, _, _, _, width, height, depth, flags = struct.unpack('<BBBHHBHHHHBB', source[:18])
    out_w = 1 << (width - 1).bit_length()
    out_h = 1 << (height - 1).bit_length()
    if (width, height) == (out_w, out_h):
        continue
    assert cmap == 0 and kind == 2 and depth in (24, 32), name
    stride = depth // 8
    pixels = source[18 + id_size:18 + id_size + width * height * stride]
    assert len(pixels) == width * height * stride
    output = bytearray(struct.pack('<BBBHHBHHHHBB', 0, 0, 2, 0, 0, 0, 0, 0, out_w, out_h, 32, 8))
    # TGA output is bottom-left origin. Normalize the source origin explicitly.
    for y in range(out_h):
        sy = min(height - 1, int((y + .5) * height / out_h))
        if flags & 32:
            sy = height - 1 - sy
        for x in range(out_w):
            sx = min(width - 1, int((x + .5) * width / out_w))
            if flags & 16:
                sx = width - 1 - sx
            offset = (sy * width + sx) * stride
            pixel = pixels[offset:offset + stride]
            output.extend(pixel if stride == 4 else pixel + b'\xff')
    (target / name).write_bytes(output)
    converted.append(name)
    print(f'PASS: {name}: {width}x{height} -> {out_w}x{out_h}, BGRA32')

manifest = ['-- Generated by backport-tools/prepare_unitframe_textures.py.',
            'local _, ns = ...', 'local paths = {}',
            'ns.Wrath.BarTexturePaths = paths']
for name in converted:
    old = 'Interface\\AddOns\\EllesmereUI\\media\\textures\\' + name
    new = 'Interface\\AddOns\\EllesmereUIUnitFrames\\Media\\Textures_335\\' + name
    manifest.append(f'paths[ [[{old.lower()}]] ] = [[{new}]]')
(root / 'EllesmereUIUnitFrames/EUI_UnitFrames_335_Textures.lua').write_text('\n'.join(manifest) + '\n', encoding='utf-8')
