"""Encode the Core art the unit frames draw outside the bar catalogue as
module-owned Wrath TGAs (3.3.5 loads neither PNG nor non-power-of-two TGA).

Resamples each image to the next power of two (whole-image texcoords and the
class sprite's relative coords stay valid), writes uncompressed BGRA32, and
emits EUI_UnitFrames_335_Media.lua, which adds the old Core paths to the
adapter's texture redirect table. Core files stay untouched.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
core = root / 'EllesmereUI/media'
target = root / 'EllesmereUIUnitFrames/Media/Art_335'
SOURCES = [
    'combat/combat0.tga', 'combat/combat1.tga', 'combat/combat2.tga',
    'combat/combat3.tga', 'combat/combat4.tga', 'combat/combat5.tga',
    'combat/combat-indicator-custom.png', 'combat/combat-indicator-class-custom.png',
]


def pot(n):
    return 1 << (n - 1).bit_length()


lines = ['-- Generated by backport-tools/prepare_unitframe_media.py.',
         'local _, ns = ...', 'local paths = ns.Wrath.BarTexturePaths']
for rel in SOURCES:
    img = Image.open(core / rel).convert('RGBA')
    w, h = img.size
    # The class sprite is drawn ~22px per cell; 512 keeps 128px cells.
    size = (min(512, pot(w)), min(512, pot(h)))
    if size != img.size:
        img = img.resize(size, Image.LANCZOS)
    out_rel = Path(rel).with_suffix('.tga')
    out = target / out_rel
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out, compression=None)
    print(f'PASS: {rel}: {w}x{h} -> {size[0]}x{size[1]}, BGRA32')
    old = 'Interface\\AddOns\\EllesmereUI\\media\\' + rel.replace('/', '\\')
    new = 'Interface\\AddOns\\EllesmereUIUnitFrames\\Media\\Art_335\\' + str(out_rel).replace('/', '\\')
    lines.append(f'paths[ [[{old.lower()}]] ] = [[{new}]]')
(root / 'EllesmereUIUnitFrames/EUI_UnitFrames_335_Media.lua').write_text('\n'.join(lines) + '\n', encoding='utf-8')
